name: CI for triggers
run-name: triggers review!
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, closed, synchronize, reopened ]
    branches:
      - '**/releases'
    paths:
      - '**.py'
  issues:
    types: [ opened, edited, closed ]
  schedule:
    - cron: 30 5,17 17 7 0 
  workflow_dispatch: 

jobs:
  myTriggerExample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python hello-world.py
