name: variables example
run-name: variablesv1

on:
  workflow_dispatch:
    inputs:
      my_name:
        description: 'my_name variable'
        type: string
        required: true
        default: Test

env:
  my_env_name: 'envTest'

jobs:
  myJob:
    runs-on: ubuntu-latest
    steps: 
      - name: INPUT STEP
        run: echo 'this is an input variable:${{ inputs.my_name }}'
      - name: ENV STEP
        run: echo 'this is a workflow variable:${{ env.my_env_name }}'
      - name: REPO STEP
        run: echo 'this is a repo variable:${{ vars.REPOVARIABLE }}'
